### PR TITLE
[Docs] Change source chart

### PR DESCRIPTION
**Pull request by ymrsmns**
- Upgrade source image for chart 
- Update Readme

### CODE REVIEW

**Comment by ymrsmns** [comment]
@scDisorder Please update outdated documentation

**Comment by scDisorder** [comment]
oh, just saw that
I would like to, but I can't :)
but if you bump minor version of the [chart](https://github.com/chartmuseum/charts/blob/main/src/chartmuseum/Chart.yaml#L4) to v3.1.1 to pass CI, I think it can be merged as some of maintainers able to check this PR

**Comment by ymrsmns** [comment]
why can't we merge it?

**Comment by ymrsmns** [comment]
@scDisorder why can't we merge it?

**Comment by scDisorder** [comment]
@ymrsmns 
I do not have rights to do it, mate
I'm just a contributor

**Comment by ymrsmns** [comment]
@jdolitsky could you take MR

**Comment by jdolitsky** [comment]
@ymrsmns - sorry that I missed this. Would love to get these updates if you can rebase and bump chart version

**Comment by ymrsmns** [comment]
> @ymrsmns - sorry that I missed this. Would love to get these updates if you can rebase and bump chart version

I`am  bump chart version

**Comment by ymrsmns** [comment]
@jdolitsky up

**Review by jdolitsky — APPROVED** [review]
Thanks again!

**Pull request merged**
