### PR TITLE
Add podLabels field

### PR DESCRIPTION
**Pull request by hazim1093**
Add standard podLabels field to allow additional labels on pods

### CODE REVIEW

**Comment by BernhardGruen** [comment]
Hey,

I would like to see this feature in future versions of the Chartmuseum Chart. Is there any reason not to merge this PR?

Many thanks in advance

Bernhard

**Review by cbuto — CHANGES_REQUESTED** [review]
thanks @hazim1093!

a few more small changes then its good to go:

1. we'll need to bump the chart version to `3.8.0`
1. `podLabels` needs to be added to the [README](https://github.com/chartmuseum/charts/blob/main/src/chartmuseum/README.md#configuration) (in the `configuration` table)

**Comment by hazim1093** [comment]
@cbuto right, just updated those 👍

**Review by cbuto — APPROVED** [review]

**Comment by cbuto** [comment]
thanks for your contribution @hazim1093!

**Pull request merged**
