### PR TITLE
Helm chart for chartmuseum-ui

### PR DESCRIPTION
**Pull request by raresociopath**
Related to: https://github.com/chartmuseum/ui/issues/23
I suggest that we have one chartmuseum chart with subcharts for all components.

### CODE REVIEW

**Comment by jdolitsky** [comment]
@raresociopath thanks for opening and getting this repo started 

- do you think we can remove the top level Chart.yaml / values.yaml ?

**Comment by raresociopath** [comment]
@jdolitsky sure!

**Comment by raresociopath** [comment]
@jdolitsky do you also want me to remove charts folder and move the ui chart to the root of the repo?

**Comment by jdolitsky** [comment]
@raresociopath - if you're still interested in adding the UI chart, this repo is now functional

**Pull request closed without merging**
