### PR TITLE
bump version up to 1.13.1

### PR DESCRIPTION
**Pull request by scDisorder**
hello there!
bumped the version and added `.gitignore` file, if it appreciable

### CODE REVIEW

**Comment by scDisorder** [comment]
not sure why exactly CI failed, but i think it may be `.gitignore` file

**Review by jdolitsky — APPROVED** [review]

**Comment by scDisorder** [comment]
I also think that #9 must be merged at first, then we can bump chart version up to 3.1.0

**Comment by jdolitsky** [comment]
@scDisorder - can you rebase? #9 is merged. You can use chart version 3.1.0

**Comment by mkilchhofer** [comment]
I would rebase the 3 commits into 1 or squash-merge this PR.

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
